// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjv1ukchXV5u3eouxXjkeC7JO9bJYr8WE',
    appId: '1:148517961897:web:c41a9d914d6c40284869b8',
    messagingSenderId: '148517961897',
    projectId: 'mynotesapp-bb6bc',
    authDomain: 'mynotesapp-bb6bc.firebaseapp.com',
    storageBucket: 'mynotesapp-bb6bc.appspot.com',
    measurementId: 'G-JTWTX8FLZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsYJT5O4Z6--1NkDn1jiDNIYEwYvWa5sg',
    appId: '1:148517961897:android:43f1b58f760b96374869b8',
    messagingSenderId: '148517961897',
    projectId: 'mynotesapp-bb6bc',
    storageBucket: 'mynotesapp-bb6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG682p_wLxp6g_A638DJSz1JsZWkDqi9Y',
    appId: '1:148517961897:ios:3df81679a7d698bb4869b8',
    messagingSenderId: '148517961897',
    projectId: 'mynotesapp-bb6bc',
    storageBucket: 'mynotesapp-bb6bc.appspot.com',
    iosBundleId: 'com.testapp.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG682p_wLxp6g_A638DJSz1JsZWkDqi9Y',
    appId: '1:148517961897:ios:3df81679a7d698bb4869b8',
    messagingSenderId: '148517961897',
    projectId: 'mynotesapp-bb6bc',
    storageBucket: 'mynotesapp-bb6bc.appspot.com',
    iosBundleId: 'com.testapp.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjv1ukchXV5u3eouxXjkeC7JO9bJYr8WE',
    appId: '1:148517961897:web:ad5797970308469c4869b8',
    messagingSenderId: '148517961897',
    projectId: 'mynotesapp-bb6bc',
    authDomain: 'mynotesapp-bb6bc.firebaseapp.com',
    storageBucket: 'mynotesapp-bb6bc.appspot.com',
    measurementId: 'G-5JYDKNXH73',
  );
}
